trigger:
  - master
  - AndroidX
  - refs/tags/*

variables:
  BUILD_NUMBER: $[counter('$(Build.SourceBranchName)_counter', 1)]
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>
#   SUPPORT_MERGED_DLL_URL: <url to AndroidSupport.Merged.dll>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/dev/signing-job
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin
      ref: refs/heads/dev/templating

jobs:
  - template: .ci/prepare.yml@components
    parameters:
      masterBranchName: 'AndroidX'
  - template: .ci/build.yml@components
    parameters:
      cakeTemplatesBranch: 'dev/templating'
      tools:
        - 'xamarin.androidbinderator.tool': '0.3.0'
        - 'xamarin.androidx.migration.tool': '1.0.0-preview03'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
